FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=turbostake/turbostake
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY turbostake.tar.gz /turbostake.tar.gz
RUN tar -xvf /turbostake.tar.gz

#ADD . /turbostake
RUN cd /turbostake/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /turbostake && scripts/windows-crosscompile/compile-turbostake.sh
